# Generated by Django 2.1.1 on 2019-04-17 11:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AOF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SECTOR_ID', models.FloatField(max_length=50)),
                ('SECTOR_NAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DONOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DONOR_ID', models.FloatField(max_length=50)),
                ('NAME', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='INSTITUTIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INSTITUTION_ID', models.FloatField(max_length=50)),
                ('NAME', models.CharField(max_length=50)),
                ('CONTACT', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NGO_ID', models.FloatField(max_length=50)),
                ('NGO_NAME', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('INSTIT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisApp.INSTITUTIONS')),
                ('SECTOR_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisApp.AOF')),
            ],
        ),
        migrations.CreateModel(
            name='Ngoprojs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.FloatField(max_length=20, null=True)),
                ('project_na', models.CharField(max_length=200)),
                ('org_interv', models.FloatField(max_length=50)),
                ('donor_id', models.FloatField(max_length=50)),
                ('sectors_ID', models.FloatField(max_length=50)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField(null=True)),
                ('Geographic', models.CharField(max_length=50)),
                ('budget_num', models.FloatField(max_length=50)),
                ('budget_cur', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('project_name', models.CharField(max_length=30)),
                ('donor', models.CharField(max_length=30)),
                ('project_description', models.CharField(max_length=30)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Subcounties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('adm2_en', models.CharField(max_length=50)),
                ('adm2_pcode', models.CharField(max_length=50)),
                ('adm1_en', models.CharField(max_length=50)),
                ('adm1_pcode', models.CharField(max_length=50)),
                ('adm0_en', models.CharField(max_length=50)),
                ('adm0_pcode', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('validon', models.DateField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='donor',
            name='NGO_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gisApp.NGO'),
        ),
    ]
