# Generated by Django 2.1.1 on 2019-04-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aof',
            name='SECTOR_ID',
            field=models.FloatField(max_length=2),
        ),
    ]
