# Generated by Django 2.1.1 on 2019-04-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gisApp', '0003_auto_20190417_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='INSTIT_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='NGO_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='SECTOR_ID',
            field=models.IntegerField(),
        ),
    ]
